[2025-04-30T03:00:41.110+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-30T03:00:41.115+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_ca_top10.load_current_weather scheduled__2025-04-30T02:00:00+00:00 [queued]>
[2025-04-30T03:00:41.118+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_ca_top10.load_current_weather scheduled__2025-04-30T02:00:00+00:00 [queued]>
[2025-04-30T03:00:41.118+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-04-30T03:00:41.121+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_current_weather> on 2025-04-30 02:00:00+00:00
[2025-04-30T03:00:41.126+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=8761) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-30T03:00:41.126+0000] {standard_task_runner.py:72} INFO - Started process 8764 to run task
[2025-04-30T03:00:41.126+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_ca_top10', 'load_current_weather', 'scheduled__2025-04-30T02:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/weather_ca_top10.py', '--cfg-path', '/tmp/tmphp1rttcr']
[2025-04-30T03:00:41.127+0000] {standard_task_runner.py:105} INFO - Job 37: Subtask load_current_weather
[2025-04-30T03:00:41.145+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_ca_top10.load_current_weather scheduled__2025-04-30T02:00:00+00:00 [running]> on host 975c9d700231
[2025-04-30T03:00:41.176+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_ca_top10' AIRFLOW_CTX_TASK_ID='load_current_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-04-30T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-30T02:00:00+00:00'
[2025-04-30T03:00:41.176+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-30T03:00:41.181+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-04-30T03:00:41.181+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-04-30T03:00:41.182+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-04-30T03:00:41.182+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-30T03:00:41.943+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-30T03:00:42.152+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-30T03:01:15.873+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-04-30T03:01:15.878+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-30T03:01:15.909+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-30T03:01:15.912+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_ca_top10, task_id=load_current_weather, run_id=scheduled__2025-04-30T02:00:00+00:00, execution_date=20250430T020000, start_date=20250430T030041, end_date=20250430T030115
[2025-04-30T03:01:15.965+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-30T03:01:16.179+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-04-30T03:01:16.217+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
