[2025-05-01T00:48:07.422+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-01T00:48:07.427+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_ca_top10.load_current_weather manual__2025-05-01T00:47:55.732545+00:00 [queued]>
[2025-05-01T00:48:07.429+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_ca_top10.load_current_weather manual__2025-05-01T00:47:55.732545+00:00 [queued]>
[2025-05-01T00:48:07.429+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-01T00:48:07.432+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_current_weather> on 2025-05-01 00:47:55.732545+00:00
[2025-05-01T00:48:07.437+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_ca_top10', 'load_current_weather', 'manual__2025-05-01T00:47:55.732545+00:00', '--job-id', '76', '--raw', '--subdir', 'DAGS_FOLDER/weather_ca_top10.py', '--cfg-path', '/tmp/tmpk55qn77i']
[2025-05-01T00:48:07.438+0000] {standard_task_runner.py:105} INFO - Job 76: Subtask load_current_weather
[2025-05-01T00:48:07.438+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=812) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-01T00:48:07.439+0000] {standard_task_runner.py:72} INFO - Started process 821 to run task
[2025-05-01T00:48:07.452+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_ca_top10.load_current_weather manual__2025-05-01T00:47:55.732545+00:00 [running]> on host a70fb8b05a55
[2025-05-01T00:48:07.479+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_ca_top10' AIRFLOW_CTX_TASK_ID='load_current_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T00:47:55.732545+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-01T00:47:55.732545+00:00'
[2025-05-01T00:48:07.480+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-01T00:48:07.483+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-05-01T00:48:07.484+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-05-01T00:48:07.484+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-05-01T00:48:07.484+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-05-01T00:48:08.426+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-01T00:48:08.567+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-01T00:48:26.605+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-01T00:48:26.615+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-01T00:48:26.663+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-01T00:48:26.664+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_ca_top10, task_id=load_current_weather, run_id=manual__2025-05-01T00:47:55.732545+00:00, execution_date=20250501T004755, start_date=20250501T004807, end_date=20250501T004826
[2025-05-01T00:48:26.729+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-01T00:48:26.757+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-01T00:48:26.758+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
