[2025-05-01T07:00:19.969+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-01T07:00:19.974+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_ca_top10.load_current_weather scheduled__2025-05-01T06:00:00+00:00 [queued]>
[2025-05-01T07:00:19.977+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_ca_top10.load_current_weather scheduled__2025-05-01T06:00:00+00:00 [queued]>
[2025-05-01T07:00:19.977+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2025-05-01T07:00:19.980+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): load_current_weather> on 2025-05-01 06:00:00+00:00
[2025-05-01T07:00:19.987+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=769) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-01T07:00:19.987+0000] {standard_task_runner.py:72} INFO - Started process 772 to run task
[2025-05-01T07:00:19.987+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_ca_top10', 'load_current_weather', 'scheduled__2025-05-01T06:00:00+00:00', '--job-id', '106', '--raw', '--subdir', 'DAGS_FOLDER/weather_ca_top10.py', '--cfg-path', '/tmp/tmpqgou4qtr']
[2025-05-01T07:00:19.989+0000] {standard_task_runner.py:105} INFO - Job 106: Subtask load_current_weather
[2025-05-01T07:00:20.006+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_ca_top10.load_current_weather scheduled__2025-05-01T06:00:00+00:00 [running]> on host 049272b42e61
[2025-05-01T07:00:20.038+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_ca_top10' AIRFLOW_CTX_TASK_ID='load_current_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-05-01T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-05-01T06:00:00+00:00'
[2025-05-01T07:00:20.039+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-01T07:00:20.045+0000] {base.py:84} INFO - Retrieving connection 'snowflake_conn'
[2025-05-01T07:00:20.046+0000] {connection.py:413} INFO - Snowflake Connector for Python Version: 3.12.1, Python Version: 3.12.5, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.36
[2025-05-01T07:00:20.047+0000] {connection.py:1196} INFO - Connecting to GLOBAL Snowflake domain
[2025-05-01T07:00:20.047+0000] {connection.py:1277} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-05-01T07:00:22.042+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-01T07:00:22.293+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-01T07:00:43.730+0000] {cursor.py:1156} INFO - Number of results in first chunk: 1
[2025-05-01T07:00:43.737+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-05-01T07:00:43.780+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-01T07:00:43.782+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_ca_top10, task_id=load_current_weather, run_id=scheduled__2025-05-01T06:00:00+00:00, execution_date=20250501T060000, start_date=20250501T070019, end_date=20250501T070043
[2025-05-01T07:00:43.847+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-05-01T07:00:43.874+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-01T07:00:43.875+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
